### ISSUE TITLE
Incompatible Version of Koa-Router

### ISSUE THREAD

**Issue by mcmar** [ktonon/koa-s3-sign-upload#2]
This is using koa-router v7.1.0, which using the koa2 promise-based syntax. But you're using the koa1 generator syntax, which is no longer supported. This library should either downgrade to koa-router v5.4.1 or change the syntax to the promise-based koa2 syntax. I tried both approaches and both seem to work for me. I'm not sure how it's worked for you before. Perhaps you have an older version of koa-router installed in the parent app that this is finding?

**Comment by ktonon** [comment]
Sorry for the delay. Just looking at this now. Yes, you are correct, the parent app was using `^5.4.0`. Thanks for the fix

**Comment by ktonon** [comment]
Fixed by #3. Published to npm as `1.0.3`
