### ISSUE TITLE
Using context in signS3 options argument

### ISSUE THREAD

**Issue by JonathanWbn** [ktonon/koa-s3-sign-upload#9]
I would like to do something like this:
```
app.use(signS3((ctx) => ({
  bucket: 'MyS3Bucket',
  keyPrefix: ctx.request.headers.host
})))
```

I tried the following, but that didn't work either:
```
app.use((ctx, next) => signS3({
  bucket: 'MyS3Bucket',
  keyPrefix: ctx.request.headers.host
})(ctx, next))
```

Is there any way I can use the ctx object?

**Comment by JonathanWbn** [comment]
Any updates on this?

**Comment by TLevesque** [comment]
Does anyone have some clue on how to do this?

**Comment by JonathanWbn** [comment]
Solved here: https://stackoverflow.com/questions/46474264/using-ctx-in-koa-middlware/46502440#46502440
